[package]
name = "tama-io"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Bioinformatics format I/O for TAMA (noodles wrappers)"
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"

[dependencies]
tama-core.workspace = true
anyhow.workspace = true
thiserror.workspace = true
log.workspace = true
flate2.workspace = true
# noodles-* added via cargo add
