[package]
name = "tama-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Core domain model and algorithms for TAMA"
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
indexmap.workspace = true
log.workspace = true
